version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: cartype-backend-run
        image: cartype-backend:dev
        ports:
            - "11001:8080"
        environment:
          - NODE_ENV=production
        env_file:
          - .env